const menu = [
  const menu = [
    {
      id: 1,
      title: "fluffy pancakes",
      category: "breakfast",
      price: 15.99,
      img: "./images/item-1.jpeg",
      desc: `Soft and golden pancakes with a side of chill — served with a copper mug of cold brew bliss.`,
    },
    {
      id: 2,
      title: "double stack burger",
      category: "lunch",
      price: 13.99,
      img: "./images/item-2.jpeg",
      desc: `Thick beef patties layered with raw denim attitude and a splash of gochujang heat.`,
    },
    {
      id: 3,
      title: "monster milkshake",
      category: "shakes",
      price: 6.99,
      img: "./images/item-3.jpeg",
      desc: `Loaded with vintage vibes, street art swirls, and an organic cherry on top.`,
    },
    {
      id: 4,
      title: "sunny side special",
      category: "breakfast",
      price: 20.99,
      img: "./images/item-4.jpeg",
      desc: `Bright flavors with retro charm — pork belly, toast, and a hint of truffaut nostalgia.`,
    },
    {
      id: 5,
      title: "power egg sandwich",
      category: "lunch",
      price: 22.99,
      img: "./images/item-5.jpeg",
      desc: `A bold bite: vegan-approved, farm-to-table eggs, with a side of vintage kickstarter energy.`,
    },
    {
      id: 6,
      title: "cookie cream blast",
      category: "shakes",
      price: 18.99,
      img: "./images/item-6.jpeg",
      desc: `Dreamy blend of Oreos and heirloom flair, all wrapped in a nostalgic hipster twist.`,
    },
    {
      id: 7,
      title: "crispy bacon roll",
      category: "breakfast",
      price: 8.99,
      img: "./images/item-7.jpeg",
      desc: `Crisp bacon, normcore-friendly layers, and a sprinkle of viral brunch buzz.`,
    },
    {
      id: 8,
      title: "roadside classic",
      category: "lunch",
      price: 12.99,
      img: "./images/item-8.jpeg",
      desc: `Old-school American flavors with a twist of squid ink rebellion and food truck flair.`,
    },
    {
      id: 9,
      title: "lockdown shake",
      category: "shakes",
      price: 16.99,
      img: "./images/item-9.jpeg",
      desc: `Smooth, rich, and deeply comforting — the perfect companion for any cozy night in.`,
    },
  ];
  