const menu = [
  {
    id: 1,
    title: "golden pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Fluffy stacks with artisan syrup, cold-pressed vibes, and a side of copper mug charm.`,
  },
  {
    id: 2,
    title: "double deck burger",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `A juicy pair of patties layered with denim flavor and gochujang heat, thundercats approved.`,
  },
  {
    id: 3,
    title: "thunder shake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Viral-level milkshake packed with chillwave sweetness, booth-worthy flavors, and a 3-wolf punch.`,
  },
  {
    id: 4,
    title: "countryside bliss",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Retro flavors and pork belly magic meet austin-style morning delight with shabby chic charm.`,
  },
  {
    id: 5,
    title: "veggie burst sandwich",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Vegan layers, retro sauce, and a pop-up twist — where farm meets fashion.`,
  },
  {
    id: 6,
    title: "cookie rush shake",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Chia and cream shake with a Portland soul and a splash of craft brew cool.`,
  },
  {
    id: 7,
    title: "bacon blast",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Crispy bacon, cloud bread softness, and an Icelandic twist to start your day strong.`,
  },
  {
    id: 8,
    title: "heritage classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `A timeless bite featuring squid essence, leggings crunch, and a hint of street-style flavor.`,
  },
  {
    id: 9,
    title: "lockdown shake",
    category: "shakes",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Crafted for cozy nights — microdosed sweetness and synth spirit with an edison twist.`,
  },
];
